2.33. Разметка главной страницы
htmlacademy-htmlcss/435773-device-32 pull request #2
Opened 2021-09-28 10:23 UTC by Okksana

2021-09-28 11:56 UTC, mkolotovich requested changes

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +            <ul class="header-services-list">
Этот список я думаю избыточен. Достаточно четырех элементов в списке page-navigation-list

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +             <ul class="simple-catalog-list">
Вот эти три списка лучше объеденить в один список.

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +            <img class="slider-image" src="" alt="Самая длинная палка для селфи!">
Вот эти изображения положите каждый внутрь своей секции вместе с кнопками Предыдущий товар и Следующий товар

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +                <td><span>50м</span></td>
Теги span здесь избыточны

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +                <td><span>48 часов</span></td>
Тут тоже span избыточен

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +                <td><span>Карбон</span></td>
Тут тоже span ни к чему. Лучше разметить через th теги здесь чем через td

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +            </ol>
Это можно разметить с помощью формы с 3мя радиобатонами внутри

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +              <span class="services-tab-button">Кредит</span>
Это лучше сделать интерактивными элементами, как вариант можно использовать кнопки

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +            <dt><b>Кредит</b></dt>
По моему это заголовки)

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +            Доставим редкий товар под заказ <span class="tip">i</span>
Я думаю, что этот текст лучше разметить через параграф, а в кнопку положить только tip

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +          <p><b>Подпишитесь на рассылку</b></p>
Это я бы тоже разметил заголовком, а заголовок выше бы убрал

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +            <label><input class="mailing-checkbox-free" type="checkbox" name="its-free" checked> Это бесплатно</label>
По моему это просто текст, а не чекбокс)

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +          </address>
Телефон разметьте как в секции Контакты

2021-09-28 11:56 UTC, mkolotovich commented on index.html
> +        </section>
Я бы разметил подвал немного по другому. В два ряда и в 3 строки в каждом ряду. Мне кажется так удобнее будет строить сетку)

2021-09-28 14:25 UTC, Okksana commented on index.html
> +            <ul class="header-services-list">
+

2021-09-28 14:29 UTC, Okksana commented on index.html
> +             <ul class="simple-catalog-list">
+

2021-09-28 14:47 UTC, Okksana commented on index.html
> +            <img class="slider-image" src="" alt="Самая длинная палка для селфи!">
+

2021-09-28 14:51 UTC, Okksana commented on index.html
> +                <td><span>48 часов</span></td>
+

2021-09-28 14:51 UTC, Okksana commented on index.html
> +                <td><span>Карбон</span></td>
+

2021-09-28 15:58 UTC, Okksana commented on index.html
> +              <span class="services-tab-button">Кредит</span>
+

2021-09-28 16:03 UTC, Okksana commented on index.html
> +          <p><b>Подпишитесь на рассылку</b></p>
+

2021-09-28 16:05 UTC, Okksana commented on index.html
> +            <label><input class="mailing-checkbox-free" type="checkbox" name="its-free" checked> Это бесплатно</label>
+

2021-09-29 11:13 UTC, Okksana commented on index.html
> +            </ol>
+

2021-09-29 12:01 UTC, Okksana commented on index.html
> +        </section>
+

2021-09-29 12:24 UTC, mkolotovich commented on index.html
> +            <img class="slider-image" src="" alt="Самая длинная палка для селфи!">
Изображения всё таки лучше вложить внутрь каждого блока slider-buttons

2021-09-29 12:30 UTC, mkolotovich commented on index.html
> +          </address>
А зачем ссылку в тег address вкладываете?

2021-09-29 12:35 UTC, mkolotovich requested changes
Исправьте 2 замечания с предыдущей проверки и мердж

2021-09-29 12:38 UTC, Okksana commented on index.html
> +            <img class="slider-image" src="" alt="Самая длинная палка для селфи!">
+

2021-09-29 12:58 UTC, merged