Сетка страницы и крупных блоков на флексах для главной страницы
htmlacademy-htmlcss/435773-device-32 pull request #6
Opened 2021-11-17 12:09 UTC by Okksana

2021-11-17 14:18 UTC, mkolotovich requested changes
Исправьте замечания

2021-11-17 14:18 UTC, mkolotovich commented on css/styles.css
> +	flex-grow: 1;
К чему здесь это свойство? Оно ни на что не влияет, так что можете убирать его

2021-11-18 08:33 UTC, Okksana commented on css/styles.css
> +
+

2021-11-18 08:34 UTC, Okksana commented on css/styles.css
> +
+

2021-11-18 08:34 UTC, Okksana commented on css/styles.css
> +	margin: 0 auto;
+

2021-11-18 08:35 UTC, Okksana commented on css/styles.css
+

2021-11-18 09:39 UTC, Okksana commented on css/styles.css
> +	flex-grow: 1;
+

2021-11-18 09:39 UTC, Okksana commented on css/styles.css
> +	justify-content: space-between;
+

2021-11-18 09:49 UTC, mkolotovich requested changes
удалите элемент `<h2 class="visually-hidden">Мы в социальных сетях</h2>` он даёт пустое пространство под футером

2021-11-18 10:20 UTC, Okksana commented on css/styles.css
> +
и второй +

2021-11-18 10:38 UTC, merged